version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY_URL

  build:
    commands:
      - echo Building Docker image...
      - cd api
      - docker build --build-arg STAGE=prod -t $ECR_REPOSITORY_NAME:$IMAGE_TAG .
      - docker tag $ECR_REPOSITORY_NAME:$IMAGE_TAG $ECR_REGISTRY_URL/$ECR_REPOSITORY_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $ECR_REGISTRY_URL/$ECR_REPOSITORY_NAME:$IMAGE_TAG


  post_build:
    commands:
      - echo Updating ECS task definition...
      - task_definition=$(aws ecs register-task-definition --family task-definition-family --container-definitions file://path-to-container-definitions.json)
      - task_revision=$(echo $task_definition | jq '.taskDefinition.revision')
      - echo Updating ECS service with new task definition...
      - aws ecs update-service --cluster cluster-name --service service-name --task-definition task-definition-family:$task_revision